### ISSUE TITLE
(node) sys is deprecated. Use util instead.

### ISSUE THREAD

**Issue by SoyaDokio** [sunny/edith#28]
_(node) sys is deprecated. Use util instead._
`Cakefile#1` is using require('sys') which has been deprecated in Node 4.0.0.
```shellscript
- {print} = require 'sys'
+ {print} = require 'util'
```

**Comment by sunny** [comment]
Hi @SoyaDokio! Thank you for submitting this!

Edith's stack is a bit outdated and would probably benefit from using a better build system, but for now I guess this simple fix should suffice.
