### ISSUE TITLE
On a page not found, ctrl-e should switch to the edit page

### ISSUE THREAD

**Issue by sunny** [sunny/edith#35]
Currently a page that does not exist only shows "page not found" and does not accept the same keyboard shortcuts as the other pages.

**Comment by andrewten45** [comment]
Hello, I would like to contribute. When I go to [https://edit.sunfox.org/1234](url) without previously visiting it, it shows "Edit me!". Once I press the key bind `Ctrl + e,` it directs me to: "Page not found. Create me!", which can't be edited, nor do key binds work there. Am I understanding this correctly if the intended result is to switch back to the edit page?

**Comment by sunny** [comment]
Hi there! Yes, the “Page not found” should listen to `ctrl + e`, like the html page does when the page exists.

**Comment by andrewten45** [comment]
Upon searching within this repo, it seems like there is an "event" that allows the `Ctrl + e` functionality to happen, specifically within the public/html.js & public/script.js files. I take note of this, likely needing the same function later. Within lib/routes.php, this appears to be where the "Page not found. Create me!" text is housed.

**Comment by andrewten45** [comment]
I did some testing. One solution is to remove this block: `if (!$page_exists) {
    header('HTTP/1.0 404 Not Found');
    die("Page not found: <a href=".EDITH_URI."/".$page->name.">Create me!</a>");
  }`. Afterwards, it seems to display the intended functionality described in this issue. Could it be that the `die()` at the end was causing the issue?

**Comment by sunny** [comment]
In some way, yes, it is: it’s showing a small HTML page with a link to edit the page.

Ideally we would still keep the fact that the `.html` version for a non-existing page would:
- respond a 404 error code (good practice)
- visually explain to the user that the page does not exist (clearer than an empty page saying "Edit me!")

I feed that it’s ok if the page does not have a link, though.

**Comment by andrewten45** [comment]
I think I have a solution, then. Using `echo` I was able to put the 404 message in that scenario when the page doesn't exist. The page still listens to keyboard input. I'll create a PR.

**Comment by sunny** [comment]
Fixed in v2.0.1 and deployed to https://edit.sunfox.org/page-not-found.html. Thank you @andrewten45 🎉
