### ISSUE TITLE
Protect page editing with a password

### ISSUE THREAD

**Issue by bndn** [sunny/edith#7]
Write a user and a password at the top of the textarea to protect the page from editing with a HTTP Basic Auth.
A solution with one line :

```
user: my_username, password: my_password
content of the file…
```

A solution with a [YAML Front Matter](https://github.com/mojombo/jekyll/wiki/YAML-Front-Matter) like Jekyll :

```

---
user: my_username
password: my_password

---
content of the file…
```

These credentials must be invisible from all others representations.

**Comment by sunny** [comment]
Closing in favor of #24
